### PR TITLE
Update to use Dialog functionality

### PR DESCRIPTION
**Pull request by dogboydog**
No pressure to merge if you don't want to, but I updated the script as a demonstration of the new [Dialog functionality](https://github.com/mapeditor/tiled/pull/3384) in Tiled 1.9. 

I also fixed a typo and usages of console.error (use tiled.error instead now)

https://user-images.githubusercontent.com/9920963/177224568-6aea8848-553c-4375-af6a-d2fa01f10491.mp4

I only had one example to try with (the example you linked to from OGA) so not sure if I covered every condition

### CODE REVIEW

**Comment by lukas-shawford** [comment]
This looks awesome!

One minor thing I noticed is when the dialog initially opens, it says "Current Direction: Down" at the top, but in the combo box just below, "Right" is selected by default. So it seems the UI is a bit out of sync with the actual default state:

image

There are also some great tileset examples in the `tests` directory. One thing I noticed is with `test_tileset_rect1.tsx` tileset, I wasn't able to get it to animate all the way through with these options:

image

It's supposed to loop 1 all the way through 9 (and then a blank square at the end), but it only goes 1 through 5:

08EC1149-F811-460C-B796-9962FE0ACD53

Seems something might be off with the stride calculation.

I'll do a bit more testing later this week - but I'm eager to get this merged, this is a huge improvement!

**Comment by dogboydog** [comment]
Nice thanks. The initial text one should be easy to fix. Not sure what I messed up with the stride.

**Comment by dogboydog** [comment]
I have fixed the initial display of direction but not sure yet what is wrong with the stride.

**Comment by lukas-shawford** [comment]
Hey, sorry I didn't get a chance to look into this further until just now. I just pushed a couple additional commits to fix the issue I noticed earlier. Basically just needed to recalculate `config.frames` by calling `getMaxFrames` when changing direction. I'll get this merged and publish a new release in a minute. Thanks for contributing!

**Comment by dogboydog** [comment]
No problem, thanks for accepting. Sorry it wasn't 100% working

**Comment by lukas-shawford** [comment]
Just released as version 1.3 - thanks again!

https://github.com/lukas-shawford/tiled-bulk-animations/releases/tag/v1.3

**Pull request merged**
